openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
security:
- okta: []
paths:
  /health/hello:
    get:
      tags:
      - health-controller
      operationId: health
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /health/auth:
    get:
      tags:
      - health-controller
      operationId: healthAuth
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /game/{id}:
    get:
      tags:
      - game-controller
      operationId: getGame
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/GameResponse"
  /game-types/:
    get:
      tags:
      - game-type-controller
      operationId: get
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GameTypeResponse"
components:
  schemas:
    GameResponse:
      type: object
      properties:
        uciFen:
          type: string
        whitePlayer:
          $ref: "#/components/schemas/User"
        blackPlayer:
          $ref: "#/components/schemas/User"
        whitePlayerRating:
          type: number
          format: float
        blackPlayerRating:
          type: number
          format: float
        whiteEloChange:
          type: number
          format: float
        blackEloChange:
          type: number
          format: float
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        lastMoveTime:
          type: string
          format: date-time
        blackTimeLeft:
          type: integer
          format: int64
        whiteTimeLeft:
          type: integer
          format: int64
        result:
          type: string
        resultDetail:
          type: string
      required:
      - blackTimeLeft
      - whiteTimeLeft
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        sub:
          type: string
        email:
          type: string
        name:
          type: string
    GameTypeResponse:
      type: object
  securitySchemes:
    okta:
      type: oauth2
      scheme: bearer
      bearerFormat: JWT
      flows:
        authorizationCode:
          authorizationUrl: https://dev-l5aemj1026u4dqia.us.auth0.com/authorize
          tokenUrl: https://dev-l5aemj1026u4dqia.us.auth0.com/oauth/token
          scopes:
            openid: openid
            email: email
            profile: profile
