/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {User} from './user';

export interface GameResponse {
    uciFen?: string;
    whitePlayer?: User;
    blackPlayer?: User;
}
