name: Spring Boot Unit Tests

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Set up JDK 21
        uses: actions/setup-java@v4 # Action to set up Java Development Kit
        with:
          java-version: '21' # Specify the Java version for your Spring Boot app
          distribution: 'temurin' # Recommended distribution for Adoptium (formerly AdoptOpenJDK)
          cache: 'maven' # Cache Maven dependencies for faster builds

      - name: Run Maven Unit Tests
        # Navigate to the backend directory and run Maven's 'test' phase.
        # By default, 'mvn test' executes unit tests (managed by maven-surefire-plugin)
        # and skips integration tests (typically managed by maven-failsafe-plugin,
        # which runs in later phases like 'integration-test' or 'verify').
        run: |
          mvn test
